<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title></title>
        <link rel="stylesheet" href="/asset/styles.css" type="text/css" />
    </head>
    <body>
        <header>
            
        </header>

    <?php if (isset($flash_message)): ?>
        <?= $flash_message; ?>
        <br />
        <hr />
    <?php endif; ?>

    <hr />

    <?php if (isset($user)): ?>

        Logged In As: <?= $user->getName(); ?>
        | <a href="/logout">Logout</a>
        <hr />

    <?php elseif ($_SERVER['REQUEST_URI'] != '/login'): ?>

        <a href="/login">Login</a>

    <?php endif; ?>
