<?php include 'common/header.phtml'; ?>

<h1>H1</h1>

    <form action="/submit" method="POST" class="form">
        Url:
        <br />
        <input type="text" name="url" />
        <br />
        
        Rant:
        <br />
        <textarea name="rant" rows="10" cols="80"></textarea>
        <br />
        <input type="submit" value="Submit Rant" class="btn" />
    </form>
        


<?php include 'common/footer.phtml'; ?>